### PR TITLE
Bump asciidoctor-epub3 to 1.5.0-alpha.12

### PR DESCRIPTION
**Pull request by slonopotamus**
I was not planning to release alpha-12 so soon, but I had because of asciidoctor/asciidoctor-epub3#269 regression.

### CODE REVIEW

**Comment by slonopotamus** [comment]
Oh, kindlegen, why can't you just work... Investigating.

**Comment by slonopotamus** [comment]
I believe we hit jruby/jruby#5971.

**Comment by slonopotamus** [comment]
Submitted a workaround to kindlegen: tdtds/kindlegen#38.

**Comment by slonopotamus** [comment]
The question is - why this doesn't happen on asciidoctor-epub3 CI.

**Comment by robertpanzer** [comment]
I am seeing the same error locally on OSX:
```
Building native extensions. This could take a while...
ERROR:  Error installing /Users/robertpanzer/.gradle/caches/modules-2/files-2.1/rubygems/kindlegen/3.0.5/d5fdb8bd945a9d08050acfd92a6591a4e570ad28/kindlegen-3.0.5.gem:
        ERROR: Failed to build gem native extension.

    current directory: /Users/robertpanzer/dev/asciidoctorj-epub3/asciidoctorj-epub3/build/.gems/gems/kindlegen-3.0.5/ext
/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/java -cp :/Users/robertpanzer/.gradle/caches/modules-2/files-2.1/org.jruby/jruby-complete/9.2.9.0/8e44ce7a1417966d89957bd766a148601e28828b/jruby-complete-9.2.9.0.jar org.jruby.Main -rrubygems /Users/robertpanzer/dev/asciidoctorj-epub3/asciidoctorj-epub3/build/.gems/gems/rake-13.0.1/exe/rake RUBYARCHDIR=/Users/robertpanzer/dev/asciidoctorj-epub3/asciidoctorj-epub3/build/.gems/extensions/universal-java-11/2.5.0/kindlegen-3.0.5 RUBYLIBDIR=/Users/robertpanzer/dev/asciidoctorj-epub3/asciidoctorj-epub3/build/.gems/extensions/universal-java-11/2.5.0/kindlegen-3.0.5
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.headius.backport9.modules.Modules (file:/Users/robertpanzer/.gradle/caches/modules-2/files-2.1/org.jruby/jruby-complete/9.2.9.0/8e44ce7a1417966d89957bd766a148601e28828b/jruby-complete-9.2.9.0.jar) to method sun.nio.ch.NativeThread.signal(long)
WARNING: Please consider reporting this to the maintainers of com.headius.backport9.modules.Modules
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
curl http://kindlegen.s3.amazonaws.com/KindleGen_Mac_i386_v2_9.zip -L -o KindleGen_Mac_i386_v2_9.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  4 10.0M    4  456k    0     0   422k      0  0:00:24  0:00:01  0:00:23  422k
 86 10.0M   86 8947k    0     0  4291k      0  0:00:02  0:00:02 --:--:-- 4289k
100 10.0M  100 10.0M    0     0  4742k      0  0:00:02  0:00:02 --:--:-- 4739k
rake aborted!
Errno::ENOENT: No such file or directory - No such file or directory
/Users/robertpanzer/dev/asciidoctorj-epub3/asciidoctorj-epub3/build/.gems/gems/kindlegen-3.0.5/ext/Rakefile:34:in `block in create_task_for_unix'
/Users/robertpanzer/dev/asciidoctorj-epub3/asciidoctorj-epub3/build/.gems/gems/rake-13.0.1/exe/rake:27:in `<main>'
Tasks: TOP => default => install => kindlegen => KindleGen_Mac_i386_v2_9.zip
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /Users/robertpanzer/dev/asciidoctorj-epub3/asciidoctorj-epub3/build/.gems/gems/kindlegen-3.0.5 for inspection.
Results logged to /Users/robertpanzer/dev/asciidoctorj-epub3/asciidoctorj-epub3/build/.gems/extensions/universal-java-11/2.5.0/kindlegen-3.0.5/gem_make.out
```

Trying out a similar command the one that is failing also fails for me though:
```
$ sh "curl https://github.com/asciidoctor/asciidoctor"
sh: curl https://github.com/asciidoctor/asciidoctor: No such file or directory
```
I guess at least when running sh is just a bash this should be run as `sh -c "curl https://..."`, no?

**Comment by robertpanzer** [comment]
Forget my comment, it was stupid, this is Ruby code, not shell, so it should be sth else.

**Comment by slonopotamus** [comment]
We're currently discussing the situation in asciidoctor/asciidoctor-epub3#272.

**Comment by slonopotamus** [comment]
Okay, I believe asciidoctorj-epub3 cannot use alpha-12.

**Pull request closed without merging**
